import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header/Header";
import { ClerkProvider } from '@clerk/nextjs'
import Footer from "./Components/Footer/Footer";
import { EdgeStoreProvider } from './lib/edgestore';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Globetrotter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <EdgeStoreProvider>
          {children}
          </EdgeStoreProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
